### ISSUE TITLE
ComboBox dropdown background gets cut off by viewport

### ISSUE THREAD

**Issue by jenewland1999** [IHIutch/draft-ui#1]
Hi 👋🏻

Saw this component library in a Tweet on my timeline and took a quick look as always great to see new projects pop up. Looks great so far, keep up the great work! 🙌🏻

Found a small visual bug with ComboBox where the background only extends to the height of the viewport and therefore if the viewport height is tiny the items in the ComboBox extend beyond the background, which looks a bit 💩.

Did my best to highlight the bug in the screenshot below.

![image](https://user-images.githubusercontent.com/34895363/235765542-f7d8de75-5290-4ea0-90de-d9a2720df9f8.png)

This is in Chrome v112 on macOS, just in case it's browser or platform specific. 

Hope this helps 😃

**Comment by IHIutch** [comment]
Thank you kindly. And thanks for the issue 🙏

**Comment by IHIutch** [comment]
https://github.com/IHIutch/draft-ui/commit/da2df9301042d09f167a029c5d18dd1f68dc8dc3 Should fix the broken UI issue. Waiting to hear back on the suggested approach to handling overflowing popovers though. Given that popovers receive a height style with the available height for the popover, I'm going to assume scrolling within a popover is preferred and close this issue. 

I've updated the other popover components to behave similarly
