### ISSUE TITLE
docs: Add "edit" button to docs pages so people can easily report issues or submit PR's

### ISSUE THREAD

**Issue by IHIutch** [IHIutch/draft-ui#12]

**Comment by henrikvtcodes** [comment]
If nobody else is working on this, I'd like to take this on :)

**Comment by IHIutch** [comment]
Go for it! This maybe could be broken into two features, since feedback and edit are two different things. But excited to see what you come up with

**Comment by henrikvtcodes** [comment]
Gotcha - I'll try to tackle the page editing first

**Comment by henrikvtcodes** [comment]
Alright - I added both a page edit link and feedback link copying the Panda CSS example pretty much verbatim, in PR #23

**Comment by IHIutch** [comment]
Closed by #23
