### ISSUE TITLE
docs: Add darkmode logo

### ISSUE THREAD

**Issue by IHIutch** [IHIutch/draft-ui#13]

**Comment by jolbol1** [comment]
can add className dark:invert onto the logo to achieve this 
![image](https://github.com/IHIutch/draft-ui/assets/5064896/b3e9e5f0-82f9-4e67-8b61-7611966db3bf)

If that is what you meant.

**Comment by IHIutch** [comment]
You're on the ball, thanks!

**Comment by IHIutch** [comment]
Fix: https://github.com/IHIutch/draft-ui/commit/9642a050fdc0735635cb44996f3d4ac656c2ca26
