### ISSUE TITLE
Add CLI (or use sly)

### ISSUE THREAD

**Issue by kentcdodds** [IHIutch/draft-ui#5]
A CLI for "installing" things would be nice. And could be relatively easy by using [Sly CLI](https://sly-cli.fly.dev/) by @JacobParis. That comes with the benefit of sharing the maintenance burden as well.

Thoughts on a collaboration here?

**Comment by IHIutch** [comment]
I think this would be a great addition and I'd love to make it easier for folks use. Admittedly, this is something I'm not super familiar with but would happy to collab! 

One thing that concerns me is that I haven't wrapped my head around is making changes in the future. Maintaining a library is not something I've done before so I'd like to make sure I have a good understanding what types of changes come with more/less risk using this approach. I haven't looked into that much.

**Comment by jolbol1** [comment]
Good idea, I dont think it would be hard to get sly up and running for now. Plus given you have kept the implementation of the components to just tailwind and not config files needed I dont think a custom CLI would even be needed at this point.

In terms of making changes in the future I dont think you need to worry. With this type of copy-paste library I think the burden is on the user to be aware of this. If you update a component they can pull in a fresh one from the cli, but need to be aware that if they have modified this themselves beyond your defaults it will be overwritten. The riskier change is if you modify the structure in some way so their existing components no longer work, but again, I think its on the user to either make the required changes or just keep the previous version of the component in their repo.

**Comment by jacobparis** [comment]
I've merged the changes so Sly users can now select Draft UI and install from there

re: ongoing updates
- from a clean working tree, users can install and overwrite the components and then use the git diff view to see if there's any changes they want to port back over. This isn't ideal, but users are in charge of their own code 
- Sly could offer a --merge flag of some sort that would run a sort of git merge over the existing files and write the conflict markers, so the IDE would show it as a merge conflict and then users can pick/choose their changes at that time
- If users are allowed to check for updates and pull in changes from the registry, then we'd need a way of storing the local "version" of each component so Sly doesn't bug people indefinitely to update. That would probably require adding a list of added files to the sly.json (similar to the "dependencies" field in a package.json)
- there is a `version` field in each registry and in each item. Currently nothing is being done with that and they're all at 1.0.0

**Comment by IHIutch** [comment]
Thank you all so much for your help with this <3
